### ISSUE TITLE
Error adding second time entry (our first bug!)

### ISSUE THREAD

**Issue by DotNetDublin** [BlazingSaddlesSolutions/TimeKeeper#36]
On either the Client or Server project if I add a time entry and then select to add another entry I receive the below error which I haven't been able to track down.

```
blazor.server.js:21 [2021-05-14T12:20:08.331Z] Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at TimeKeeper.Services.ClientService.GetAllAsync() in C:\Users\franc\source\repos\BlazingSaddlesSolutions\TimeKeeper\TimeKeeper.Services\ClientService.cs:line 44
   at TimeKeeper.ComponentLibrary.Components.AddTimeEntry.OnAfterRenderAsync(Boolean firstRender) in C:\Users\franc\source\repos\BlazingSaddlesSolutions\TimeKeeper\TimeKeeper.ComponentLibrary\Components\AddTimeEntry.razor.cs:line 33
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

![Error](https://user-images.githubusercontent.com/52583820/118269979-3ff57d80-b4b7-11eb-8ff3-836b136aba46.png)

**Comment by DotNetDublin** [comment]
Closing issue as no longer found since the simplified branch was pulled into main.
